name: "Resources"
output_dir: "_site"
navbar:
  title: "R-esources"
  left:
  - text: "Home"
    href: index.html
  - text: "visuaRization"
    href: visuarization.html
  - text: "wRiting R Markdown"
    href: writingrmarkdown.html
  - text: "aRtistry"
    href: artistry.html
output:
  html_document:
theme: jekyll-theme-architect
