name: "Resources"
navbar:
  title: "R-esources"
  href: index.html
  title: "visuaRization"
  href: visuarization.html
  title: "wRiting R Markdown"
  href: writingrmarkdown.html
  title: "aRtistry"
  href: artistry.html
output:
  html_document:
theme: jekyll-theme-architect
